# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analytics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analytics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61nalytics.proto\x12\tanalytics\"*\n\x15StudentMetricsRequest\x12\x11\n\tmatricula\x18\x01 \x01(\x05\"\xc7\x01\n\x16StudentMetricsResponse\x12\x11\n\tmatricula\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x10\n\x08promedio\x18\x03 \x01(\x02\x12\x1a\n\x12materias_aprobadas\x18\x04 \x01(\x05\x12\x1b\n\x13materias_reprobadas\x18\x05 \x01(\x05\x12\x17\n\x0fnivel_desempeno\x18\x06 \x01(\t\x12&\n\x1elatencia_calculo_microsegundos\x18\x07 \x01(\x03\"R\n\x10TelemetryRequest\x12\x11\n\tcampus_id\x18\x01 \x01(\t\x12\x15\n\rtotal_eventos\x18\x02 \x01(\x05\x12\x14\n\x0cintervalo_ms\x18\x03 \x01(\x05\"w\n\x0eTelemetryEvent\x12\x13\n\x0bsequence_id\x18\x01 \x01(\x05\x12\x0e\n\x06sensor\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\x12\x0e\n\x06unidad\x18\x04 \x01(\t\x12\x0e\n\x06\x65stado\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\t2\xbf\x01\n\x10\x41nalyticsService\x12X\n\x11GetStudentMetrics\x12 .analytics.StudentMetricsRequest\x1a!.analytics.StudentMetricsResponse\x12Q\n\x15StreamCampusTelemetry\x12\x1b.analytics.TelemetryRequest\x1a\x19.analytics.TelemetryEvent0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STUDENTMETRICSREQUEST']._serialized_start=30
  _globals['_STUDENTMETRICSREQUEST']._serialized_end=72
  _globals['_STUDENTMETRICSRESPONSE']._serialized_start=75
  _globals['_STUDENTMETRICSRESPONSE']._serialized_end=274
  _globals['_TELEMETRYREQUEST']._serialized_start=276
  _globals['_TELEMETRYREQUEST']._serialized_end=358
  _globals['_TELEMETRYEVENT']._serialized_start=360
  _globals['_TELEMETRYEVENT']._serialized_end=479
  _globals['_ANALYTICSSERVICE']._serialized_start=482
  _globals['_ANALYTICSSERVICE']._serialized_end=673
# @@protoc_insertion_point(module_scope)
