# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """=============================================================================
    CONTRATO PROTOBUF (.proto)
    =============================================================================
    Define las estructuras binarias y los métodos RPC con tipos estrictos.
    Cada campo tiene un número de etiqueta (1, 2, 3...) que se codifica
    directamente en binario, ahorrando el envío de strings como en JSON.
    =============================================================================

    Servicio gRPC de Alta Velocidad para Comunicación Backend-to-Backend
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStudentMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetStudentMetrics',
                request_serializer=analytics__pb2.StudentMetricsRequest.SerializeToString,
                response_deserializer=analytics__pb2.StudentMetricsResponse.FromString,
                _registered_method=True)
        self.StreamCampusTelemetry = channel.unary_stream(
                '/analytics.AnalyticsService/StreamCampusTelemetry',
                request_serializer=analytics__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=analytics__pb2.TelemetryEvent.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """=============================================================================
    CONTRATO PROTOBUF (.proto)
    =============================================================================
    Define las estructuras binarias y los métodos RPC con tipos estrictos.
    Cada campo tiene un número de etiqueta (1, 2, 3...) que se codifica
    directamente en binario, ahorrando el envío de strings como en JSON.
    =============================================================================

    Servicio gRPC de Alta Velocidad para Comunicación Backend-to-Backend
    """

    def GetStudentMetrics(self, request, context):
        """1. RPC Unario: Petición y Respuesta clásica ultrarrápida (<1ms)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCampusTelemetry(self, request, context):
        """2. RPC Server Streaming: Transmisión en vivo de telemetría de servidores/campus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStudentMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudentMetrics,
                    request_deserializer=analytics__pb2.StudentMetricsRequest.FromString,
                    response_serializer=analytics__pb2.StudentMetricsResponse.SerializeToString,
            ),
            'StreamCampusTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCampusTelemetry,
                    request_deserializer=analytics__pb2.TelemetryRequest.FromString,
                    response_serializer=analytics__pb2.TelemetryEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """=============================================================================
    CONTRATO PROTOBUF (.proto)
    =============================================================================
    Define las estructuras binarias y los métodos RPC con tipos estrictos.
    Cada campo tiene un número de etiqueta (1, 2, 3...) que se codifica
    directamente en binario, ahorrando el envío de strings como en JSON.
    =============================================================================

    Servicio gRPC de Alta Velocidad para Comunicación Backend-to-Backend
    """

    @staticmethod
    def GetStudentMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetStudentMetrics',
            analytics__pb2.StudentMetricsRequest.SerializeToString,
            analytics__pb2.StudentMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCampusTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/analytics.AnalyticsService/StreamCampusTelemetry',
            analytics__pb2.TelemetryRequest.SerializeToString,
            analytics__pb2.TelemetryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
